name: Deploy Prod (pm2)

on:
  push:
    branches: [ "prod" ]

concurrency:
  group: deploy-prod
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT}}
          script: |
            set -e

            APP_DIR=/home/niv/kantine
            BRANCH=prod

            cd $APP_DIR

            echo "== Pull latest =="
            git fetch --all
            git checkout $BRANCH
            git reset --hard origin/$BRANCH

            echo "== Reload pm2 =="
            pm2 reload kantine --update-env

            pm2 save
            echo "Deploy done"
